//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kojin.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kojin_Country
    {
        public string cou_code { get; set; }
        public string name { get; set; }
        public string cou_name { get; set; }
        public string iso3 { get; set; }
        public Nullable<int> numcode { get; set; }
    }
}
