//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kojin.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kojin_Item_Unit_Master
    {
        public string Unit_Name { get; set; }
        public Nullable<int> Unit_Status { get; set; }
        public Nullable<System.DateTime> Unit_DateTime { get; set; }
    }
}
