//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kojin.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kojin_Item_Replanishment
    {
        public string Cust_Id { get; set; }
        public string Kit_Id { get; set; }
        public string Rep_Window { get; set; }
        public string Reorder_value { get; set; }
        public Nullable<int> Item_Rep_Status { get; set; }
        public Nullable<System.DateTime> Item_Rep_DateTime { get; set; }
        public int Item_Rep_Sno { get; set; }
    }
}
