//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kojin.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kojin_Kitchen_Tray_Master
    {
        public string Kit_id { get; set; }
        public string Tray_Id { get; set; }
        public Nullable<int> No_Of_Cell { get; set; }
        public string D_Cell_1 { get; set; }
        public string D_Cell_2 { get; set; }
        public string D_Cell_3 { get; set; }
        public string D_Cell_4 { get; set; }
        public string D_Cell_5 { get; set; }
        public string D_Temp_1 { get; set; }
        public Nullable<int> D_Status { get; set; }
        public Nullable<System.DateTime> D_DateTime { get; set; }
    }
}
