//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kojin.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kojin_Item_Master
    {
        public string Item_Cat_id { get; set; }
        public string Item_id { get; set; }
        public string Item_Name { get; set; }
        public string Item_Desc1 { get; set; }
        public string Item_Desc2 { get; set; }
        public string Item_UnitMeasure { get; set; }
        public Nullable<int> Item_Status { get; set; }
        public Nullable<System.DateTime> Item_DateTime { get; set; }
    }
}
